#ifndef CONFIG_H
#define CONFIG_H

#define PROJECT "@PROJECT_NAME@"

#define PROJECT_VERSION "@PROJECT_VERSION@"

#define PROJECT_VERSIONED_NAME "@PROJECT_NAME@ v@PROJECT_VERSION@"

#define PROJECT_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"

#define PROJECT_VERSION_MINOR "@PROJECT_VERSION_MINOR@"

#define PROJECT_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif
